### PR TITLE
Issue 126 add cim identity options

### LINKED ISSUE #126: SecurityOptions - Could not infer CimType from the provided .NET object
Hi,

I'm running into issues with a baseline in windows 2019. 
I receive the following error on multiple securityOptions:

```
Could not infer CimType from the provided .NET object.
    + CategoryInfo          : InvalidOperation: (Microsoft.Manag...InstanceCommand:) [], CimException
    + FullyQualifiedErrorId : New-CimInstance,Microsoft.Management.Infrastructure.CimCmdlets.NewCimInstanceCommand
    + PSComputerName        : localhost
 
The PowerShell DSC resource '[SecurityOption]SecuritySetting(INF): EnableGuestAccount' with SourceInfo ************** threw one or more non-terminating errors while running the Test-TargetResource functionality. These errors ar
e logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost
```

Does anyone know how to resolve this?

Regards,
Thijs

### PR DESCRIPTION
**Pull request by ccunning**
#### Pull Request (PR) description
Added support for more SDDL SID constants [Issue #126]

#### This Pull Request (PR) fixes the following issues
- Fixes #126 

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/securitypolicydsc/142)

### CODE REVIEW

**Comment by ccunning** [comment]
Hey, I have not received anything about the license CLA. I'm not sure if the bot is stuck, or what is going on, but the check has been stuck for 12 hours. Is there any way I can get that passed, or have the check restarted?

Any help would be appreciated. Thanks!

**Comment by gaelcolas** [comment]
Hi @ccunning,
Thanks for the contribution.
Sorry for the delay, but if we take too long, feel free to come on the DSC channel of the PowerShell slack/discord and remind us: https://powershell.slack.com/ (register here http://slack.poshcode.org/)

Since the repositories have been transferred outside of Microsoft, the CLA bot should have been disabled and is not required anymore (I'll fix that shortly).
Also, before those changes can be released, this repository should be moved to the new CI pipeline automation as described here: https://dsccommunity.org/blog/convert-a-module-for-continuous-delivery

This is only for releases, merging PRs is ok as long as the tests/quality work through AppVeyor.

**Comment by ccunning** [comment]
Hey @gaelcolas, Thanks for getting back to me on this. No worries on the delay, I know everyone is busy.

In order for me to be able to submit the pull request without the license/cla check, then, should I just close this PR and open up a new one? What's the best next step?

**Comment by johlju** [comment]
You don’t have to do anything. We will just remove the “required” (branch protection rule) for the CLA status check.

**Comment by gaelcolas** [comment]
Which I just did for the dev branch.
Also, as I said:

> Also, before those changes can be released, this repository should be moved to the new CI pipeline automation as described here: dsccommunity.org/blog/convert-a-module-for-continuous-delivery

**Comment by ccunning** [comment]
___
*[Modules/SecurityPolicyResourceHelper/SecurityPolicyResourceHelper.psm1, line 575 at r2](https://reviewable.io/reviews/dsccommunity/securitypolicydsc/142#-M24cpfI5kTpDNRKBbWX:-M5KWRjQEayRwT9yFAAZ:bbcjw8e) ([raw file](https://github.com/dsccommunity/securitypolicydsc/blob/6829bbf237d8dfac6d6a1715deb31888f29e1749/Modules/SecurityPolicyResourceHelper/SecurityPolicyResourceHelper.psm1#L575)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> ConvertFrom-SDDLDescriptor
> ```

Can you please add unit tests for these new functions?

https://github.com/dsccommunity/SecurityPolicyDsc/blob/dev/Tests/Unit/SecurityPolicyResourceHelper.tests.ps1
</blockquote></details>

Done. I added some unit tests for ConvertFrom-SDDLDescriptor and ConvertTo-SDDLDescriptor with various possibilities.

**Comment by johlju** [comment]
I have merged this but I cannot release this since the CI pipeline has not yet been converted https://github.com/dsccommunity/SecurityPolicyDsc/issues/143

**Comment by johlju** [comment]
@ccunning Thanks for this. Great work! 😃

**Comment by ccunning** [comment]
Thanks! Glad I could help. Sorry it took me so long... things have been a little crazy.

**Comment by johlju** [comment]
No worries, I know how it is! We get this released as soon as possible.

**Pull request merged**
