### PR TITLE
BREAKING CHANGE: SecurityOption: append multiline strings with null char and newline

### PR DESCRIPTION
**Pull request by mgreenegit**
#### Pull Request (PR) description

The intention of this PR is to support multiline settings. The correct format is for each entry to end with a null character and a new line.

#### Task list

- [X] Added an entry to the change log under the Unreleased section of the file CHANGELOG.md.
      Entry should say what was changed and how that affects users (if applicable), and
      reference the issue being resolved (if applicable).
- [NA] Resource documentation added/updated in README.md.
- [NA] Resource parameter descriptions added/updated in README.md, schema.mof and comment-based
      help.
- [NA] Comment-based help added/updated.
- [NA] Localization strings added/updated in all localization files as appropriate.
- [NA] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/securitypolicydsc/154)

### CODE REVIEW

**Comment by mgreenegit** [comment]
I'm not sure what needs to be done for the build automation to correctly set the version? This could be included in the next 3.0 preview.

**Comment by johlju** [comment]
> I'm not sure what needs to be done for the build automation to correctly set the version? This could be included in the next 3.0 preview.

By adding 'breaking change' to the commit message/title when merging the PR. I will update the PR title so this is done. 
I will review during the weekend.

**Comment by mgreenegit** [comment]
In testing this at length I found a more simple approach. Adding new commits. Will not require the additional function but I will add comments to explain why it is doing and why. This is still a breaking change because the expected input becomes a single string instead of a comma delimited array of strings.

**Comment by mgreenegit** [comment]
This requires a much smaller change than I thought originally. Updating PR.

**Comment by mgreenegit** [comment]
replaced by #155 155

**Pull request closed without merging**
